stages:
  - test

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip
  - python3 -V
  - pip3 install pygame

unit-test-job:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y xvfb
    - python3 test/test_fields.py
    - python3 test/test_bomb.py
    - python3 test/test_explosion.py
    - python3 test/test_powerups.py
